name: template

on:
  pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job-name:
  timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
